version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-container
    ports:
      - "33066:3306"

  spring_container_service:
    container_name: share-book
    image: github-actions-share-book:latest #
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis
    restart: "no"

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"