spring:
  servlet:
    multipart:
      enabled: true
      location: c:\\upload
      max-request-size: 300MB
      max-file-size: 50MB
  cloud:
    aws:
      credentials:
        access-key: ENC(${AWS_ACCESS_KEY})
        secret-key: ENC(${AWS_SECRET_KEY})
      region:
        static: ap-southeast-2
      s3:
        bucket: yanolza-s3-bucket

  jwt:
    secretkey: share-book-super-secret-key-2025-strong!

  profiles:
    active: dev



logging:
  level:
    org.hibernate.SQL: info
#    org.hibernate.type: trace
#    org.springframework.security: info
jasypt:
  encryptor:
    password: ${SECRETKEY}
    bean: jasyptStringEncryptor

aladin:
  api:
    key: ttbdks7299271651001
